[tox]
envlist =
    clean
    py{310,311}-django{52}
    py{312,313,314}-django{52,61}
    coverage-html
skipsdist = True
skip_missing_interpreters = True
basepython = python3.10
isolated_build = True

[gh-actions]
python =
    3.10: py310
    3.11: py311
    3.12: py312
    3.13: py313
    3.14: py314

[testenv:clean]
deps =
    coverage
setenv =
commands =
    -coverage erase

[testenv:coverage-html]
basepython = python3.10
deps =
    coverage
setenv =
commands =
    -coverage combine --append
    coverage html --include="./src/*" --omit="*/admin.py,*/test*,*/migrations/*"

[testenv:upgrade-deps]
whitelist_externals = cp
deps =
    pip-tools
setenv =

commands =
    pip-compile {posargs} --output-file requirements-django52.txt requirements/django52.txt pyproject.toml requirements/forced-upgrade.txt
    pip-compile {posargs} --output-file requirements-django61.txt requirements/django61.txt pyproject.toml requirements/forced-upgrade.txt

[testenv:coverage-xml]
basepython = python3.10
deps =
    coverage
setenv =
commands_pre =
commands =
    -coverage combine --append
    coverage xml --include="./src/*" --omit="*/admin.py,*/test*,*/migrations/*"

[testenv]
passenv = DATABASE_URL

deps =
    coverage
    -r requirements-django{env:DJANGO_VER}.txt

setenv =
    LC_ALL=C.UTF-8
    LANG=C.UTF-8
    PYTHONPATH = {toxinidir}/src
    PYTHONWARNINGS=once::DeprecationWarning
    django52: DJANGO_VER=52
    django61: DJANGO_VER=61

commands =
    coverage run -p runtests.py {posargs}
